with open("README.md", "w", encoding="utf-8") as f:
    f.write("# Network Security Monitor\n")
    f.write("### AI-Powered Real-Time Network Anomaly Detection\n\n")
    f.write("A production-grade Python application that monitors network traffic and detects anomalies using statistical ML and Claude AI (Anthropic).\n\n")
    f.write("## Features\n")
    f.write("- Real-Time Anomaly Detection using Z-score statistical engine\n")
    f.write("- Claude AI threat analysis for every CRITICAL/HIGH anomaly\n")
    f.write("- FastAPI REST endpoints for webhook event ingestion\n")
    f.write("- Multi-rule detection engine (brute force, port scanning, data exfiltration)\n")
    f.write("- Risk scoring: CRITICAL / HIGH / MEDIUM / LOW\n")
    f.write("- Structured JSON logging with AI analysis included\n\n")
    f.write("## API Endpoints\n")
    f.write("- GET / - System status\n")
    f.write("- GET /health - Health check\n")
    f.write("- POST /analyze - Ingest and analyze a network event via webhook\n")
    f.write("- GET /detections - All detections with AI analysis\n")
    f.write("- GET /report - AI-generated executive summary report\n\n")
    f.write("## Quick Start\n")
    f.write("pip install anthropic fastapi uvicorn\n")
    f.write("set ANTHROPIC_API_KEY=your-key-here\n")
    f.write("python detector.py\n\n")
    f.write("## Start API Server\n")
    f.write("python detector.py --api\n")
    f.write("Open http://localhost:8000/docs\n\n")
    f.write("## Author\n")
    f.write("Kiran Rahul Pabboju\n")
    f.write("M.S. Computer and Information Systems Security\n")
    f.write("kiranrahulpabboju@gmail.com\n")
    f.write("linkedin.com/in/pabboju-kiran-rahul\n")
print("Done!")